### ISSUE TITLE
Support Apple Silicon (ARM64)

### ISSUE THREAD

**Issue by bdkjones** [fletcher/MultiMarkdown-6#187] opened 2020-06-23 22:47 UTC
I realize it was just announced, but there are six months until ARM Macs are in the wild. To be ready for them, apps that integrate `libmultimarkdown` need to be able to build a Universal version of the library. To rebuild, they'll first need a Universal version of the MultiMarkdown library.

The CMake dependency probably complicates this transition a lot because I imagine it won't be possible to build a Universal version of `libmultimarkdown` until CMake supports ARM64.

However, because this is a blocker for any apps that include MultiMarkdown, I wanted to open the issue so progress could be tracked and any related problems could be discussed. Thanks for your help!

**Comment by fletcher** [comment] 2020-06-23 23:40
You can tweak the Xcode project to build for whatever architectures you want that Xcode supports.  It might take a while before CMake offers that as an automatic choice, or it might be possible to manually override it today.  But either way, you can adjust the Xcode project to do whatever you like.

**Comment by bdkjones** [comment] 2020-06-24 02:26
It sounds like a new version of CMake may not be required, just a tweak to the makefile:

https://mobile.twitter.com/kubamracek/status/1275545458706755584

**Comment by nickasd** [comment] 2020-09-30 11:39
I'm trying to build MultiMarkdown with the `make xcode` comand (I have Xcode 12.0.1), and I get the following error:
```
cd build-xcode; \
	cmake -G Xcode ..
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /usr/local/Cellar/cmake/3.15.1/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: MultiMarkdown-6/build-xcode/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_a1b9a -configuration Debug -hideShellScriptEnvironment && Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_a1b9a -configuration Debug -hideShellScriptEnvironment
    
    User defaults from command line:
        HideShellScriptEnvironment = YES
    
    Prepare build
    note: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
    === BUILD TARGET cmTC_a1b9a OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=arm64, VALID_ARCHS=arm64 arm64e i386 x86_64, EXCLUDED_ARCHS=(
        arm64,
        arm64e
    )).
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


-- Configuring incomplete, errors occurred!
See also "MultiMarkdown-6/build-xcode/CMakeFiles/CMakeOutput.log".
See also "MultiMarkdown-6/build-xcode/CMakeFiles/CMakeError.log".
make: *** [xcode] Error 1
```
Is this related to what you were saying above? If yes, what do I have to do to make the build work? (I'm not an expert with CMake and environment variables.)

**Comment by fletcher** [comment] 2020-10-11 14:43
I'll need to look at the `CMakeLists.txt` file -- I think it is related to `X86_64` not being the "only" architecture when building for macOS any more.

**Comment by fletcher** [comment] 2020-10-11 14:45
I *think* you can fix this when building for x86_64 by adding `SET (CMAKE_OSX_ARCHITECTURES x86_64)` *before* the `project (${My_Project_Title})` line near the top of the file.  This is likely a bandaid and a better fix is needed, and this is obviously *not* what you want to do when building for arm64.

**Comment by nickasd** [comment] 2020-10-11 17:36
Thanks a lot, that line fixed the build. Unfortunately I'm unable to support you in providing a general fix (it sounds like we need a different solution for arm64), since I know very little about CMake etc, but it would be great if someone could figure out how to fix this in the near future.

**Comment by fletcher** [comment] 2020-10-12 18:48
I am running macOS 10.15.7 on a Late 2014 Mac mini (surprisingly this machine does everything I need it to!) and using Xcode 12.0.1.  

Whether I use MultiMarkdown or a new Xcode project, I don't seem to be able to compile for arm64 (Mac), only x86_64.  I can build for arm64 for iOS (last I checked anyways).  My Architectures Build Setting shows "Standard architectures - $(ARCHS_STANDARD)" not "Standard architectures (64-bit Intel and ARM) - $(ARCHS_STANDARD)" as seen [here](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary?language=objc)

Is there something obvious I am missing?

I'm trying to come up with the proper Cmake configuration to allow universal binaries in anticipate of Silicon computers becoming widespread.

Thanks!

**Comment by fletcher** [comment] 2020-10-28 16:56
I just pushed a couple of updates.  6.6.0 uses a revised Cmake configuration that works better for me on Xcode 12 with x86_64.

I *think* it should work better when transitioning towards ARM, but have not tested it yet (I don't have an ARM machine).

Input appreciated!

**Comment by bdkjones** [comment] 2020-11-13 08:01
Thanks for jumping on this! I have a total of 24 third-party libraries to recompile for Apple Silicon and it's been a nightmare of trying to figure out most of them. It's nice to see this project staying ahead of the curve!

**Comment by bdkjones** [comment] 2020-11-13 08:27
Okay, I've built the framework for `x86_64` and `arm64`. Here's my experience:

1. Downloaded the "latest release" tag's source as a zip archive.
2. Updated Cmake to 3.18
3. Ran `make`
4. Ran `make xcode` 

This produced an error:

    CMake Error at CMakeLists.txt:166 (project):
    No CMAKE_C_COMPILER could be found. 

It sounded to me like the script couldn't find Cmake something-or-other, so I unzipped a fresh copy of the source code and then:

3. Opened the CMake GUI
4. Clicked "Configure"
5. Clicked "Generate" 
6. Selected Xcode as the generator and left all options as-is.

CMake now built the Xcode project. I opened that in Xcode and noticed that several settings were messed up by CMake:

- Architectures
- Base SDK
- Build Active Architectures Only

So, I then:

7. Opened the "libMultiMarkdown" scheme in the scheme editor and changed the build configuration from `debug` to `release`.
8. Selected the libMultiMarkdown project and adjusted the architectures to this:

<img width="1172" alt="Screen Shot 2020-11-13 at 00 25 28" src="https://user-images.githubusercontent.com/926566/99045809-bdf7bc80-2546-11eb-8e75-8cd9d9280fcf.png">

9. Selected the "libmultimarkdown" target and changed these same settings.
10. Built the project (on my x86_64 MacBook Pro)

Inspecting the compiled framework with `lipo -archs <path-to-framework> returns the expected result:

`arm64 x86_64`

**Comment by bdkjones** [comment] 2020-11-13 08:56
Hmm. I may have spoken too soon. When I attempt to USE the compiled framework in my app, I now get several errors related to undefined functions for

    token_pool_init()
    token_pool_drain()
    token_pool_free()

I think that's related to https://github.com/fletcher/MultiMarkdown-6/commit/8afd1277ca7ca09478289c08424f20f6e063a17f#diff-47babe9dd5e41858b6944d0e59f0f8656922ae67efa9f1251f4ef09d6e10ff08

In the headers I'm getting, this change is not included; I still see:

    #define kUseObjectPool_disabled 1

I can modify the header, but when I do that the Linker gives me this:

<img width="696" alt="Screen Shot 2020-11-13 at 00 55 41" src="https://user-images.githubusercontent.com/926566/99048865-f7322b80-254a-11eb-808b-2b07009b0d59.png">

I think if I modify the header BEFORE I compile the framework, that should solve this?

**Comment by fletcher** [comment] 2020-11-13 21:25
@bdkjones -- a couple of issues 

1.	If you're using `latest release` then you are missing some of the  fixes.  For this you should be using the `develop` branch.
2.	You don't need to run `make`, then `make xcode`.  `make` prepares a CMake build using gcc/clang from the command line. `make xcode` prepares an `xcodeproj` file that can be used in Xcode or `xcodebuild`.  The two are independent.  It's not harmful to run `make` first, just unnecessary. 
3.	I can't speak to the initial error you describe since I can't test it without an ARM machine. That sounds like Xcode command line utilities were not properly configured??  Or it's related  to  not using the develop branch, as above.
4.	Yes -- you have to change `#defines` before compiling.  They are compile time directives, not run time directives.  And yes, if you don't have a strong understanding of memory management, should definitely have the object pool disabled when using `libMultiMarkdown` and not `multimarkdown`.  It makes multithreaded programs much more difficult.

**Comment by bdkjones** [comment] 2020-11-14 01:12
Perfect. I'll re-build from the latest `develop` commit and confirm the Universal binary is working.

As for the token pools, I *think* I've done that correctly? My app runs the multimarkdown compiler in an separate process over XPC. It's set up like this:


<img width="1050" alt="Screen Shot 2020-11-13 at 17 08 27" src="https://user-images.githubusercontent.com/926566/99134503-dca39500-25d2-11eb-92db-6ea1dbba3cc5.png">

**Comment by fletcher** [comment] 2020-11-14 01:40
That looks right, but you have to be certain that libMultiMarkdown can only be used on a single thread at a time.  The object pool is a single shared instance, so freeing it in one thread would wreck another thread that was using it.  In a multithreaded application, that might be difficult, and *might* take more overhead and trouble than you gain in performance.

Also, it doesn't speed compiling time, it speeds processing time when converting text to HTML.

**Comment by bdkjones** [comment] 2020-11-14 01:43
Yea. As far as I know, the XPC service is single-threaded. It doesn't matter how many threads from the host application call into the service, the service has only one thread. I've tested it by pummeling the thing with hundreds of MD files to compile and have never had a crash.

By "compiling" in the comment I meant the processing of MD to HTML; not the compiling of the app in Xcode.

**Comment by bdkjones** [comment] 2020-11-14 01:48
I can also confirm that the Universal binary is working (at least on x86_64). After cloning the repo (instead of downloading the zipped source code from the latest release tag) running `make xcode` in Terminal worked perfectly. I opened the Xcode project and adjusted the settings as described in the post above. That resulted in a correct, Universal binary.

**Comment by fletcher** [comment] 2020-11-14 02:00
What were the arch settings prior to changing them?  It should have defaulted to Standard architectures and "No" to build active only.  The goal is for you not to have to manually adjust anything for standard uses of the library.

**Comment by bdkjones** [comment] 2020-11-14 02:34
These are the settings from `make xcode`:

![Screen Shot 2020-11-13 at 18 33 58](https://user-images.githubusercontent.com/926566/99137319-dddabf00-25de-11eb-9a01-b5a829e554d8.png)

**Comment by fletcher** [comment] 2020-11-14 03:54
Can you make a fresh copy of the .xcodeproj, open it, change one setting and then undo that change (in order to ensure Xcode rewrites the file), and then zip/send it to me?  I'm trying to see what is different.

On my build libMultiMarkdown has Build Active Arch Only set to No and Arch set to $(ARCHS_STANDARD).


Thanks!

(It might be a while before I get a Silicon machine, so I can test this myself yet.)

**Comment by bdkjones** [comment] 2020-11-16 07:04
My app uses 29 libraries/frameworks, so I've been using CMake a LOT. It's doing the same thing on all other libraries I'm building as well—the same settings show up in the generated Xcode project.

**Comment by fletcher** [comment] 2020-11-16 13:00
What version of CMake are you using?

**Comment by nickasd** [comment] 2020-11-22 22:38
Since updating to macOS Big Sur, I get this output for the command `make xcode`:
```
git log master..develop --format="*    %s" | sort | uniq > CHANGELOG-UNRELEASED
mkdir build-xcode 2>/dev/null
make: [build-xcode] Error 1 (ignored)
cd build-xcode; rm -rf *
cd build-xcode; \
	cmake -G Xcode ..
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
CMake Error at CMakeLists.txt:167 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:167 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "MultiMarkdown-6/build-xcode/CMakeFiles/CMakeOutput.log".
make: *** [xcode] Error 1
```
I run `xcode-select --install` as suggested on Stackoverflow, but still the same output. Anyone knows what's the problem?

**Comment by nickasd** [comment] 2020-11-24 11:46
I'm trying to run `make xcode` on macOS Big Sur, but I'm getting this error:
```
git log master..develop --format="*    %s" | sort | uniq > CHANGELOG-UNRELEASED
fatal: .git non è un repository Git (né lo è alcuna delle directory genitrici)
mkdir build-xcode 2>/dev/null
cd build-xcode; rm -rf *
cd build-xcode; \
	cmake -G Xcode ..
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
CMake Error at CMakeLists.txt:166 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:166 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "build-xcode/CMakeFiles/CMakeOutput.log".
make: *** [xcode] Error 1
```
Even running `xcode-select --install` as suggested on Stackoverflow doesn't help. Does anyone know what the problem is?

**Comment by nickasd** [comment] 2021-02-11 12:45
After uninstalling Homebrew and hence cmake, reinstalling both, and running `sudo xcode-select --reset`, it worked again.

**Comment by DivineDominion** [comment] 2021-07-11 09:18
With the CMakeList changes introduced recently, I building on Intel Macs for both architectures works. I believe this also solves building *on* an ARM Mac. Can anyone with an M1 Mac try the latest `develop` tip?

**Comment by fletcher** [comment] 2021-09-29 20:28
Closing -- I have been using libMultiMarkdown via CMake for nvUltra for quite a while and building for x86 and ARM universal binaries without trouble.

**Closed by fletcher** 2021-09-29 20:28 UTC
