### ISSUE TITLE
Problems with transclusion for streamed input on Windows^TM^

### ISSUE THREAD

**Issue by Gavin-Holt** [fletcher/MultiMarkdown-6#236] opened 2022-01-02 19:24 UTC
Hi,

I am using MultiMarkdown (Version: v6.6.0) with piped input under Windows^TM^ (8 and 10). I have been trying to Transclude a file in the same folder as the source.

Transclusion works when source files are processed directly by MultiMarkdown, but then fails when the same file is piped with type, [cat.exe](http://gnuwin32.sourceforge.net/packages/coreutils.htm) or  [Upp.exe](http://christophe.delord.free.fr/upp/) .

I have tried the following options for `Transclude Base` metadata but they all fail:

* c:\Directory\of\source\folder

* c:\Directory\of\source\folder\

* c:/Directory/of/source/folder

* c:/Directory/of/source/folder/

Is there another format of `Transclude Base` I should be using? *Or am I just using the wrong operating system*!

My primary aim is to use [Upp](http://christophe.delord.free.fr/upp/) a Lua based pre-processor and create an extendable/personalized format for note taking. I can use Lua functions from Upp to read files, but would like to fix this issue in MultiMarkdown before recommending my workflow to others.

I am not a programmer, but suspect that without a filename argument the Transclusion routine does not know where to find files?

Kind Regards Gavin Holt

An example file to run " upp.exe -p . HowTo.mmd.txt | Multimarkdown.exe -s > HowTo.html"
[HowTo.mmd.txt](https://github.com/fletcher/MultiMarkdown-6/files/7799657/HowTo.mmd.txt)

**Comment by fletcher** [comment] 2022-01-03 04:43
Duplicate of #181

**Closed by fletcher** 2022-01-03 04:43 UTC
