### ISSUE TITLE
App Hang for accented characters

### ISSUE THREAD

**Issue by PPLandry** [fletcher/MultiMarkdown-6#107] opened 2018-01-25 21:45 UTC
For characters such as é, è, â etc, multimarkdown locks up (100% cpu)
Solved by converting to UTF-8 before processing the file. Nevertheless, it should either abort or process the file, not hang
Thanks !
Pierre

**Comment by fletcher** [comment] 2018-01-25 22:48
Can you send me an example of the file that causes trouble for you?

But there will be some trouble using files that are not either ASCII or UTF-8, since it expects those two encodings.

**Comment by PPLandry** [comment] 2018-01-25 23:11
Hi,

Thanks for the quick reply !

Here is the file. It contains this text:

En particulier, je suis responsable de formation en université privée.

I run it with this command :

"C:\multimarkdown.exe" "C:\mdtmp.md" -o "C:\ItemID24992.htm"


Pierre

**Comment by fletcher** [comment] 2018-01-26 04:13
Can you send this file as an attachment?  That's the only way for me to verify what sort of encoding was used and test it myself.

Thanks!

F-

**Comment by PPLandry** [comment] 2018-01-26 15:33
Hi,

The attachment was in my reply, but here it is again ??

Pierre

**Comment by fletcher** [comment] 2018-01-26 15:34
I don't see it here either.

I wonder if github strips out attachments from email?  Perhaps it must be uploaded to the website??

https://github.com/fletcher/MultiMarkdown-6/issues/107

**Comment by PPLandry** [comment] 2018-01-26 22:18
I basically opened up Notepad, pasted the text and saved it...

If you can’t reproduce it, get back to me and I’ll try to send you the file

**Comment by fletcher** [comment] 2018-01-26 23:37
That's why I asked -- I use accented characters all the time in my testing, and they work fine.  Not to mention that MMD is used all over the world with multiple languages and character sets without difficulty.

I need the actual file you're using, not the contents.  They're actually two separate things due to the many ways that files can be encoded.  And Windows has a tendency to do things the wrong way, which makes it more complicated.

**Comment by fletcher** [comment] 2018-02-04 20:37
I'm happy to attempt to look into the issue you're having, but will need an actual file in order to do so.

Alternatively, it's a Windows issue that I can't do much about.  But it would be strange that no one else has had this issue.

If I don't hear anything, I'll close the issue and it can be reopened as needed.

**Comment by mn4367** [comment] 2018-02-04 23:28
Please find a Zip file containing 3 files with 2 encodings [here](https://www.dropbox.com/s/n4xb4mgkpezh4jh/MMD-Encoding-Tests.zip?dl=0).

The Zip contains 3 files:

- test-iso-8859-1.md (ANSI encoding/ISO-8859-1)
- test-utf8-bom.md (UTF-8 encoding with BOM)
- test-utf8.md (UTF-8 encoding without BOM)

`test-iso-8859-1.md` indeed doesn't work, it seems that MMD hangs inside an endless loop. Tested with the latest commit 73ce1a2.

Please let me know when you've downloaded the file so I can remove it from my Dropbox, thanks.

**Comment by fletcher** [comment] 2018-02-05 02:42
So yes -- the problem is not using multibyte characters.  The problem is using non-UTF-8 text encoding.  This breaks the re2c scanner.

Use UTF-8 file encoding and you're good to go!

**Closed by fletcher** 2018-02-05 02:42 UTC
