### ISSUE TITLE
How to import the libMultiMarkdown.framework in Xcode projects

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#92] opened 2017-10-17 15:39 UTC
I managed to get the Xcode project to build and emit a .framework file:

```
make
cd build
make
cd ..
make xcode
```

... then open the Xcode project and build the framework target. The result, for reference, as Zip:
[libMultiMarkdown.framework.zip](https://github.com/fletcher/MultiMarkdown-6/files/1391575/libMultiMarkdown.framework.zip)

I then embed it in a Cocoa test app as usual (embed & link). However, I fail to import the code in Swift, so I fall back to Objective-C, and still no luck:

- `@import libMultiMarkdown;` -- "Module 'libMultiMarkdown' not found"
- `#import <libMultiMarkdown.framework>` -- file not found (although it is recognized as a framework in Xcode's auto-completion and I can traverse the paths)
- `#import <libMultiMarkdown.framework/libMultiMardown>` produces errors because of non-UTF-8 characters (probably because that's a binary file and import tries to, well, import it as source)

What does compile:

    #import "libMultiMarkdown.framework/Versions/Current/include/libMultiMarkdown/libMultiMarkdown.h"

But that looks bananas. :) Is it supposed to be like this?

Even though Xcode's source code/SyntaxKit now recognizes the functions like `token_pool_init()`, the linker does not find them, so something is clearly broken in terms of project setup.

## Code

```objc
#import "TestObject.h"
#import "libMultiMarkdown.framework/Versions/Current/include/libMultiMarkdown/libMultiMarkdown.h"
#import "libMultiMarkdown.framework/Versions/Current/include/libMultiMarkdown/token.h"
#import "libMultiMarkdown.framework/Versions/Current/include/libMultiMarkdown/d_string.h"

@implementation TestObject
- (instancetype)init
{
    self = [super init];
    if (self) {
        NSLog(@"hi");
        token_pool_init();
    }
    return self;
}
@end
```

### Error

```
Undefined symbols for architecture x86_64:
  "_token_pool_init", referenced from:
      -[TestObject init] in TestObject.o
ld: symbol(s) not found for architecture x86_64
```

---

Are there any additional steps I need to adhere to?

**Comment by fletcher** [comment] 2017-10-17 19:23
All you need to do is `make xcode` once.  You then have an Xcode project in `build-xcode`.

I use:

    #import <libMultiMarkdown/libMultiMarkdown.h>

and the like.  (Depending on what you do, you may need `token.h` and some others, as you noticed.)

If you're using the Xcode build as a static framework (which is how I now use all of my C-based libraries in Objective-C applications), you may want to change the "Copy Files" build phase to use the destination "Products Directory" to simplify locating header files.  Cmake does not allow autoconfiguring that.


Alternatively, you can change the Cmake to build regular static libraries, but this required more hoop jumping to manage included header files.

**Comment by DivineDominion** [comment] 2017-10-18 06:17
The default resulting `.framework` does not work out of the box when I build it in Xcode and drag the file from the build directory into a project. So that's expected, right? I put down my steps to verify that this is what's supposed to happen, as a basis for a README extension PR or something :)


## Default macOS Build

I had to fix the build settings to not end up with a iOS build, by the way. The SDK path was reported to be "not found", so I picked one manually:
![screen shot 2017-10-18 at 08 00 39](https://user-images.githubusercontent.com/59080/31702961-7da5e1c4-b3da-11e7-8b4b-d490f2fc192d.png)

I also had to change the target platform `macos` to `macosx` to select my Mac as a target. See #93 for a fix.

The resulting `.framework` for reference: [libMultiMarkdown.framework-default.zip](https://github.com/fletcher/MultiMarkdown-6/files/1393568/libMultiMarkdown.framework-default.zip)

Dragging into a test project and then expanding the framework item to reveal headers shows nothing, which looks suspicious:

![screen shot 2017-10-18 at 08 04 01](https://user-images.githubusercontent.com/59080/31703040-fa33ec4a-b3da-11e7-862c-31413c4fe28b.png)

Also, `#import <libMultiMarkdown/libMultiMarkdown.h>` does not compile (file not found), although the "libMultiMarkdown/" part is recognized by Xcode at least.

(I had to manually embed, and thus link, the framework in the test app's target settings.)

## Static Framework

So now I changed the framework build to copy the 3 header files to the _Product Directory_ instead. That's in `build-xcode/Debug/`, where now the `include/` directory resides.

Adding this to my test project Header Search Path makes the `#import` statement compile: `$(PROJECT_DIR)/Extern/MultiMarkdown-6/build-xcode/Debug/include`

Now it works, but you have to have the framework file plus the folder with headers. 

---

Is that the most compact result? I wonder if the Xcode framework build settings could be tweaked to expose the 3 header files as public headers, and add that to a modulemap file for easier consumption by Swift.

**Comment by fletcher** [comment] 2017-10-19 13:18
I don't have much to offer in way of Swift, but can give a bit of history for context.


Brief summary of MMD/Xcode history:

1. MMD is in C, and used across all manner of devices/OS combinations. Only Mac/iOS users need Xcode.

2. For a while I had a "hard-coded" Xcode project in the repo.  Keeping it in sync with the project itself became increasingly complex and clumsy.

3. A few years back I switched (reluctantly at first) to a CMake driven build system.  I have never looked back.  The (many) hours I spent working out the configuration kinks have been repaid to me ten fold across many different projects.

4. CMake's Xcode support is limited.  I suspect their Swift support is even more limited.  That said, it appears that Apple's Swift repo uses cmake??  <https://github.com/apple/swift/blob/master/CMakeLists.txt>


My (Objective-C) workflow experience:

1. Create new Xcode project.

2. Add MMD-6 as a git submodule

3. Run `make xcode` inside MMD-6

4. Drag the .xcodeproj "file" to the master Xcode project

5. Set the Copy Files build phase on libMultiMarkdown to use "Products Directory" (this has to be done manually and is the one step that can;t be done in cmake, but it's *much* better than it used to be.)

6. Ensure that my app includes libMultiMarkdown in the "Target Dependencies" and "Link Binary with Libraries" phases.

7. Build and go.

This works for macOS and iOS (libMMD gets compiled for whichever architecture is required.)


Caveats:

1. When new versions of macOS/iOS/Xcode are installed, Cmake has to be looking at the proper version of Xcode and the SDKs.  On occasion, one simply has to update the SDK selection to the most recent one, but again that is an easy change.

2. If I move the project on disk, I may need to rerun "make xcode", which then requires repeating step 5 above.  Otherwise, I almost never need to rebuild the Xcode project in an existing project (unless significant changes are made to MMD such as adding new source files).

3. I don't use Swift, so can only speak to Obj-C (in fact, when I used swift, I intentionally used the swift command line build tools to try and stick with a cmake like experience.)



Summary:

1. For Obj-C, the only step that could reasonably be better is step 5. I've spoken to a CMake dev, and it doesn't sound like anything is going to happen.  But in that discussion, I at least got things to where they are now -- a single click in a pop-up menu.  I can live with it, especially since everything else then happens automatically.  It used to be a nightmare (both with and without cmake).

2. If better CMake settings are available, I am happy to look at changing them.

3. I'm hesitant to include a static .xcodeproj inside the repo based on how that worked the last time.


F-

**Comment by bdkjones** [comment] 2018-03-28 06:13
I just discovered this thread after running into the same issues. It would be great to have a more thorough "build" doc in the project that explains this.

**Comment by DivineDominion** [comment] 2018-03-28 06:24
Good to know I'm not alone :) If you end up using this, we could team up in a PR. Once I find out how to properly interface with MMD from Swift for syntax highlighting, I'll definitely be writing about that. This library is a gem, and it's way too hard to make use of :)

**Comment by bdkjones** [comment] 2018-03-28 06:27
Ha, I'm afraid I won't be much help with Swift. You'll have to pry C pointers from my cold, dead hands.

**Comment by nickasd** [comment] 2019-05-25 22:21
I'm also having difficulty getting this to work. Even though after adding the framework as a Target Dependency, adding it to Link Binary With Libraries and creating a Copy Files phase building works just fine and I can see in the Finder that the framework is added to the product's Frameworks directory, I don't get any autosuggestion when typing `import <multimarkdown`.

So I tried just adding the `multimarkdown` executable as a dependency, since all I want is just being able to convert a markdown file to html. But now building doesn't work anymore and I get the error
```
clang: error: no such file or directory: 'MultiMarkdown-6-develop/build-xcode/Debug/libMultiMarkdown.framework/Versions/A/libMultiMarkdown'
Command Ld failed with a nonzero exit code
```
I can confirm that the directory `build-xcode/Debug` doesn't exist. Any idea what is going on?

**Comment by fletcher** [comment] 2019-05-26 00:25
You would need to use `#import <libMultiMarkdown/libMultiMarkdown.h>` for one thing.

Also, it appears autocomplete doesn't work in Xcode 10 unless you have the closing `>`??  Weird, but true (for me anyways).

You would need to use `libMultiMarkown` as a dependency, unless you were going to include `multimarkdown` as a separate binary inside a package directory, and call out to the shell in order to use it.

Otherwise, the instructions above should work (I've done it more times than I should have in the last couple of months on two different macOS/Xcode versions), with the caveat that Xcode 10 works differently, and now you sometimes need to make sure to  embed binaries in addition to linking them.  But not always.  Typically the problem occurs when you try to archive rather than just run your project.  But that's an Xcode issue, not a MMD issue, as far as I can tell (I had similar problems with other projects).

**Comment by nickasd** [comment] 2019-05-26 09:41
Thank you for your fast response!
Yes, I just want to call out to the shell.
It still doesn't work for me. Am I doing something wrong? You can reproduce the compile error by doing the following:
1. Create an empty macOS Cocoa App project, Objective-C.
2. Copy the `MultiMarkdown-6-develop` folder to the project root folder, where the `.xcodeproj` file resides.
3. Run `make xcode`, which results in the `build-xcode` directory being created.
4. Drag `build-xcode/MultiMarkdown.xcodeproj` into the project, so that it's nested immediately below the root item in the project navigator.
5. Add `MultiMarkdown.xcodeproj/Products/libMultiMarkdown.framework/libMultiMarkdown` and `MultiMarkdown.xcodeproj/Products/multimarkdown` as a target dependency.

    <img width="729" alt="Bildschirmfoto 2019-05-26 um 11 36 29" src="https://user-images.githubusercontent.com/26737509/58379932-82f87680-7faa-11e9-899a-6de22a5d1d8c.png">
6. Compiling will result in the error
    ```
    clang: error: no such file or directory: 'problem/MultiMarkdown-6-develop/build-xcode/Debug/libMultiMarkdown.framework/Versions/A/libMultiMarkdown'
    Command Ld failed with a nonzero exit code
    ```

**Comment by fletcher** [comment] 2019-05-26 12:00
1) I'm not sure that you can add an independent program as a dependency like that.  If all you want is to include a copy of multimarkdown inside your app, why not build it separately and do that?  Otherwise, remove `multimarkdown` and leave `libMultiMarkdown`.  If you really want to build a command line program and include the program as a separate resource in your own app, then you'll have to figure out how to do that in Xcode.  But that's separate from getting MMD itself to compile and run.

2) Make sure to follow step 5 in my list above.  You didn't mention doing that.

3) Compiles just fine for me if I otherwise follow your directions.

4) If I then also include libMultiMarkdown in the "Link Binary with libraries" I can start using it.  Since I want to use libCurl to support loading remote images and other assets, I also link to the libcurl.tbd binary in the "top-level" application and I'm off and running.

**Comment by nickasd** [comment] 2019-05-26 14:53
If not adding it as a dependency like that, then how? I want to submit the app to the App Store, so the executable has to be signed by me, and this is how I think I should do it, but even with your step 5 it doesn't work, I keep getting the same error. At which step is this folder `build-xcode/Debug` supposed to be created? Did you try building the project with signing enabled?
<img width="1259" alt="Bildschirmfoto 2019-05-26 um 16 51 11" src="https://user-images.githubusercontent.com/26737509/58383393-79850380-7fd6-11e9-9acc-3505de34b0d0.png">

**Comment by nickasd** [comment] 2019-05-26 14:56
(Note: if I remove the executable `multimarkdown` from the dependency list then it builds fine, but when adding the line `#import <libMultiMarkdown/libMultiMarkdown.h>` I get the error `'libMultiMarkdown/libMultiMarkdown.h' file not found`. Can I use this framework even just for converting a file to HTML? I couldn't find any details about how to use it.)

**Comment by fletcher** [comment] 2019-05-26 18:02
If you want to include multimarkdown as a separate binary, just build it separately and then copy `multimarkdown` to your xcode project like you would any other file.  I don't think that is the best way to go.  But if you prefer that approach, go for it.  As for compiling it within your own xcode project you'll need to figure out that part on your own as it has nothing to do with MMD itself.  There should be tons of resources online to help with that part.

Instead, I would recommend using libMultiMarkdown, so that you can access the functionality directly from your code.

I just followed your directions again on a different machine in Xcode 10.2.1, and it again works fine...  Assuming you follow step 5 above.  Signing is enabled.  I don't think signing is your problem.

I've built using this code in multiple projects, including several App Store apps.  I always do it the same way, and it always works.

I'm not sure what else to tell you, but it's not clear what is going on with your Xcode setup if you're still having problems.  I'll point out that in your screenshot you did not link to any libraries. ("(0 items)").  That may have just been when you took the image and not when you actually tried to compile.  Otherwise, you definitely have to link the library for it to be included.

I don't understand the copy files phase in the latest screenshot you sent.  Why are you doing that?


As for how to use the library, `libMultiMarkdown.h` has instructions and the API methods (pay attention to the warning at the top).  `main.c` is an example of using the library to perform an entire conversion complete with all the various options and extras (the `multimarkdown` binary is built using `libMultiMarkdown`, so it uses the same approach you would need to from your own application).

If you want even more documentation, you can install doxygen and then `make documentation` to generate HTML or LaTeX versions of documentation.  All of the information is in the source code, but it might make it "prettier".

**Comment by nickasd** [comment] 2019-05-26 18:46
I'm sorry, still not working. I must either be taking the instructions too literally and forgetting something, or I've tried too many times and obviously overseeing something. Here are screenshots of an empty project:

<img width="1189" alt="Bildschirmfoto 2019-05-26 um 20 42 54" src="https://user-images.githubusercontent.com/26737509/58385834-d7c1de80-7ff6-11e9-8f93-bf5d2cde2470.png">
<img width="1189" alt="Bildschirmfoto 2019-05-26 um 20 44 43" src="https://user-images.githubusercontent.com/26737509/58385850-18215c80-7ff7-11e9-9f44-03c0257f6e24.png">
<img width="1189" alt="Bildschirmfoto 2019-05-26 um 20 45 18" src="https://user-images.githubusercontent.com/26737509/58385857-2ec7b380-7ff7-11e9-9d9c-4d8c0ddf1f6d.png">

**Comment by nickasd** [comment] 2019-05-26 18:46
And the project.
[mm.zip](https://github.com/fletcher/MultiMarkdown-6/files/3220997/mm.zip)

**Comment by fletcher** [comment] 2019-05-26 19:08
Image # 1 -- You're looking at the `ALL_BUILD` target.  Don't mess with that.

Image # 2 -- Why is there a `Copy Files` phase there?

**Comment by nickasd** [comment] 2019-05-26 19:45
Thank you for spotting the error 🥇

> Set the Copy Files build phase on libMultiMarkdown to use "Products Directory"

You know, at first I thought you meant a build phase I had to add to my own project, and then I thought that it was more logical to do it in the subproject. It was not obvious to me that the "libMultiMarkdown" part was actually the target in the subproject, I thought you meant that the libMultiMarkdown framework should simply be added with a copy build phase.

So I'm probably going to use something like `mmd_string_convert(NULL, 0, 0, 0);`, but then this error pops up:

<img width="278" alt="Bildschirmfoto 2019-05-26 um 21 43 23" src="https://user-images.githubusercontent.com/26737509/58386380-4e62da00-7fff-11e9-94da-5758bdac384b.png">

**Comment by fletcher** [comment] 2019-05-26 19:52
That's the libCurl thing I mentioned above.

That method is probably fine, but be careful with the extensions, depending on what you need.  Default MMD behavior does not equal `0`.  `main.c` can show you what happens by default with the command line utility.  But it will still *generally* work with extensions = 0.

**Comment by nickasd** [comment] 2019-05-26 20:26
Ok, I oversaw that one. Thanks!
Now everything compiles, but I'm getting a runtime error for this simple code:

<img width="1104" alt="Bildschirmfoto 2019-05-26 um 22 23 04" src="https://user-images.githubusercontent.com/26737509/58386766-d5668100-8004-11e9-824f-43b866768fee.png">

<img width="1104" alt="Bildschirmfoto 2019-05-26 um 22 23 16" src="https://user-images.githubusercontent.com/26737509/58386768-ddbebc00-8004-11e9-8a17-ff31637c3730.png">

**Comment by fletcher** [comment] 2019-05-26 20:46
That's the instructions at the top of `libMultiMarkdown.h` that I mentioned.  ;)

**Comment by nickasd** [comment] 2019-05-26 20:52
Oh boy, now it works. Incredible! Thank you for your amazing support.

Just a suggestion from my side: it would be far more convenient to have all the instructions laid out in a single place where they are clearly visible, such as in the README. I think currently one has to find this thread to properly install the project, then read the top and the bottom of `libMultiMarkdown.h` to find the thing about the `token_pool_init()` and the options that can be passed to `mmd_string_convert` (I almost asked you what I have to pass as arguments there, and by lucky chance found the enum definitions at the bottom of the file).

Probably you're already aware of this, but there are some warnings:

<img width="262" alt="Bildschirmfoto 2019-05-26 um 22 42 02" src="https://user-images.githubusercontent.com/26737509/58387030-cbdf1800-8008-11e9-967f-a32bf3dd7a10.png">

Anyway, thanks again!

**Comment by DivineDominion** [comment] 2019-05-27 07:26
@nickasd I know how you feel :) I think a PR could be useful to include some more details.

**Comment by nickasd** [comment] 2019-07-28 17:45
Does anyone know why my PR is being ignored?
Also from #168 it looks like it can be compiled for Swift. Any instructions on how to do that?

**Comment by fletcher** [comment] 2019-07-29 12:27
I saw the comment about removing the `build` folder, which was incorrect.  And so I put further review on the backburner and was busy with lots of other things.

I see now that you reverted the `build` issue.

**Closed** 2019-07-29 12:28 UTC
Labels: help wanted
